=== KirillOsenkov/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuild/Schemas/buildschema.json
{
  "$id": "https://github.com/mhutch/MonoDevelop.MSBuildEditor",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Describes the MSBuild schema format",
  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "license": { "type": "string" },
    "items": {
      "type": "object",
      "patternProperties": {
        "^([A-Za-z_][A-Za-z\\d_-]*)$": { "$ref": "#/definitions/item" }
      },
      "additionalProperties": false
    },
    "properties": {
      "type": "object",
      "patternProperties": {
        "^([A-Za-z_][A-Za-z\\d_-]*)$": { "$ref": "#/definitions/property" }
      },
      "additionalProperties": false
    },
    "targets": {
      "type": "object",
      "patternProperties": {
        "^([A-Za-z_][A-Za-z\\d_-]*)$": { "$ref": "#/definitions/target" }
      },
      "additionalProperties": false
    },
    "intellisenseImports": {
      "type": "array",
      "items": { "type": "string" },
      "description": "Additional files to be imported at development time for IntelliSense"
    },
    "types": {
      "type": "object",
      "additionalProperties": { "$ref": "#/definitions/valueType" },
      "description": "Custom type definitions"
    },
    "metadata": {
      "type": "array",
      "items": { "$ref": "#/definitions/metadataOverride" },
      "description": "Apply metadata to existing item types"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "property": {
      "description": "Defines a property",
      "oneOf": [
        {
          "description": "Description of the property",
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string",
              "description": "Description of the property."
            },
            "type": { "$ref": "#/definitions/valueType" },
            "defaultValue": {
              "type": "string",
              "description": "The default value of the property."
            },
            "values": { "$ref": "#/definitions/valueList" },
            "isList": { "$ref": "#/definitions/valueIsList" },
            "listSeparators": { "$ref": "#/definitions/valueListSeparators" },
            "isLiteral": {
              "description": "Permit only literal values (i.e. no expressions). Defaults to false.",
              "type": "boolean",
              "default": false
            },
            "deprecationMessage": {
              "type": "string",
              "description": "Indicates that the property is deprecated and explains why."
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "item": {
      "description": "Defines an item",
      "oneOf": [
        {
          "description": "Description of the item",
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string",
              "description": "Description of the item."
            },
            "includeDescription": {
              "type": "string",
              "description": "Describes the item values listed in the Include attribute e.g. 'source files'."
            },
            "type": { "$ref": "#/definitions/valueType" },
            "metadata": {
              "type": "object",
              "patternProperties": {
                "^([A-Za-z_][A-Za-z\\d_-]*)$": { "$ref": "#/definitions/metadata" }
              },
              "additionalProperties": false
            },
            "packageType": {
              "description": "Only applies to items of type `nuget-id`. Restricts the package type."
            },
            "isSingleton": {
              "description": "Specifies that there may only be a single item of this type. This behavior is rare and unidiomatic.",
              "type": "boolean",
              "default": false
            },
            "deprecationMessage": {
              "type": "string",
              "description": "Indicates that the item is deprecated and explains why."
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "metadata": {
      "description": "Defines a metadata value",
      "oneOf": [
        {
          "description": "Description of the metadata",
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "description": { "type": "string" },
            "includeDescription": { "type": "string" },
            "type": { "$ref": "#/definitions/valueType" },
            "defaultValue": {
              "type": "string",
              "description": "The default value of the metadata."
            },
            "values": { "$ref": "#/definitions/valueList" },
            "isList": { "$ref": "#/definitions/valueIsList" },
            "listSeparators": { "$ref": "#/definitions/valueListSeparators" },
            "isRequired": {
              "description": "Whether this metadata is required on items of this type",
              "type": "boolean"
            },
            "deprecationMessage": {
              "type": "string",
              "description": "Indicates that the metadata is deprecated and explains why."
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "target": {
      "oneOf": [
        {
          "type": "string",
          "description": "Description of the target"
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string",
              "description": "Description of the target"
            },
            "deprecationMessage": {
              "type": "string",
              "description": "Indicates that the target is deprecated and explains why."
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "metadataOverride": {
      "type": "object",
      "properties": {
        "$appliesTo": {
          "description": "Item type or array of item types to which to apply this metadata",
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^([A-Za-z_][A-Za-z\\d_-]*)$"
              }
            },
            {
              "type": "string",
              "pattern": "^([A-Za-z_][A-Za-z\\d_-]*)$"
            }
          ]
        }
      },
      "patternProperties": {
        "^([A-Za-z_][A-Za-z\\d_-]*)$": { "$ref": "#/definitions/metadata" }
      },
      "additionalProperties": false
    },
    "valueList": {
      "description": "A list of valid values",
      "oneOf": [
        {
          "type": "string",
          "description": "Reference to another value list"
        },
        {
          "type": "array",
          "description": "Array of valid values"
        },
        {
          "type": "object",
          "additionalProperties": {
            "type": "string",
            "description": "Description for the value"
          }
        }
      ]
    },
    "valueIsList": {
      "description": "Whether the value permits lists. The default semicolon separator can be overridden with \"listSeparators\" property.",
      "type": "boolean",
      "default": false
    },
    "valueListSeparators": {
      "description": "Overrides the list separator characters for this value. Defaults to \";\"",
      "type": "string",
      "enum": [ ";", ",", ";," ],
      "default": ";"
    },
    "valueType" : {
      "description": "The type of the value",
      "oneOf": [
        { "$ref": "#/definitions/valueTypeRef" },
        { "$ref": "#/definitions/valueTypeIntrinsic" },
        { "$ref": "#/definitions/valueTypeCustomMinimal" },
        { "$ref": "#/definitions/valueTypeCustom" }
      ]
    },
    "valueTypeDefinition" : {
      "oneOf": [
        { "$ref": "#/definitions/valueTypeCustomMinimal" },
        { "$ref": "#/definitions/valueTypeCustom" }
      ]
    },
    "valueTypeCustomMinimal": {
      "type": "array",
      "items": { "type": "string" }
    },
    "valueTypeRef": {
      "type": "object",
      "properties": {
        "$ref": {
          "description": "JSON pointer to an existing type definition",
          "type": "string",
          "format": "json-pointer"
        }
      },
      "additionalProperties": false
    },
    "valueTypeCustom": {
      "type": "object",
      "required": [ "values" ],
      "properties": {
        "name": {
          "description": "Overrides the name displayed in the UI",
          "type": "string",
          "pattern": "^([a-z][a-z\\d-]*)$"
        },
        "description": {
          "description": "Description of the type",
          "type": "string"
        },
        "values": {
          "description": "The values this type can have",
          "type": "object",
          "additionalProperties": {
            "type": "string",
            "description": "Description of the value"
          }
        },
        "allowUnknownValues": {
          "description": "Whether to allow unknown values",
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "valueTypeIntrinsic": {
      "type": "string",
      "enum": [
        "data",
        "bool",
        "int",
        "string",
        "guid",
        "url",
        "version",
        "suffixed-version",
        "lcid",
        "culture",
        "target-name",
        "item-name",
        "property-name",
        "sdk",
        "sdk-version",
        "label",
        "importance",
        "runtime-id",
        "target-framework",
        "target-framework-version",
        "target-framework-identifier",
        "target-framework-profile",
        "target-framework-moniker",
        "nuget-id",
        "nuget-version",
        "project-file",
        "file",
        "folder",
        "folder-with-slash",
        "file-or-folder",
        "extension",
        "configuration",
        "platform",
        "project-kind-guid"
      ]
    }
  }
}

=== KirillOsenkov/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuild/Schemas/AspNetCore.buildschema.json
{
  "license": "Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for full license information.",
  "properties": {
    "AspNetCoreHostingModel": {
      "description": "Indicates whether to run an ASP.NET Core application using IIS in-process or out-of-process.",
      "type": {
        "allowUnknownValues": false,
        "values": {
          "InProcess": "Run the app using IIS in-process",
          "OutOfProcess": "Run the app using IIS out-of-process"
        }
      },
      "defaultValue": "InProcess",
      "helpUrl": "https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/in-process-hosting"
    },
    "AspNetCoreModuleName": {
      "description": "Indicates which AspNetCoreModule version to use. Versions include V1 and V2.",
      "type": [
        "AspNetCoreModuleV1",
        "AspNetCoreModuleV2"
      ]
    },
    "BlazorEnableTimeZoneSupport": {
      "description": "Indicates whether Blazor WebAssembly should include a data file to make timezone information correct. Setting this to `false` will reduce your app size.",
      "defaultValue": "true",
      "helpUrl": "https://learn.microsoft.com/aspnet/core/blazor/performance#disable-unused-features"
    },
    "RunAOTCompilation": {
      "description": "Indicates whether to run the Ahead-of-Time (AOT) compiler on the Blazor WebAssembly app. Setting this to `true` will increase runtime performance of your WebAssembly application but will also increase its deployable size.",
      "type": "bool",
      "defaultValue": "false",
      "helpUrl": "https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly#ahead-of-time-aot-compilation"
    },
    "WasmStripILAfterAOT": {
      "description": "Whether to remove .NET IL for compiled methods after WebAssembly AOT compilation",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly#trim-net-il-after-ahead-of-time-aot-compilation"
    },
    "IsTransformWebConfigDisabled": {
      "description": "Whether to prevent the SDK from transforming the `web.config` file",
      "type": "bool",
      "defaultValue": "false",
      "helpUrl": "https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/transform-webconfig"
    }
  },
  "items": {
  },
  "types": {
  }
}

=== KirillOsenkov/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuild/Schemas/Roslyn.buildschema.json
{
  "license": "Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for full license information.",
  "properties": {
    "Deterministic": {
      "description": "Enables reproducible builds, such that a given set of inputs will always produce byte-for-byte identical output",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#deterministic"

    },
    "EmitCompilerGeneratedFiles": {
      "description": "Controls whether source generated files will be saved.",
      "type": "bool"
    },
    "CompilerGeneratedFilesOutputPath": {
      "description": "Controls where source generated files are saved.",
      "type": "folder"
    },
    "ProduceReferenceAssembly": {
      "description": "Determines whether to produce a reference assembly.",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#producereferenceassembly"
    },
    "ProduceOnlyReferenceAssembly": {
      "description": "Indicates that the build should produce a reference assembly as the primary output, and not produce an implementation assembly.",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#produceonlyreferenceassembly"
    },
    "OutputAssembly": {
      "description": "The path and name of the output assembly",
      "type": "file",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#outputassembly"
    },
    "ReportAnalyzer": {
      "description": "Report additional information about analyzers, such as execution time",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#reportanalyzer"
    },
    "PublicSign": {
      "description": "Causes the compiler to mark the assembly as signed with a public key, without actually signing it",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/security#publicsign"
    },
    "ReportIVTs": {
      "description": "Causes the compiler to report information about `InternalsVisibleTo` attributes",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#reportivts"
    },
    "NoCompilerStandardLib": {
      "description": "Causes the compiler to not reference the `mscorlib` standard library. The build targets default this to `true` to suppress the compiler's implicit reference, and add an explicit reference to `mscorlib`. This explicit reference can be suppressed with the `NoStdLib` property.",
      "defaultValue": "true",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#nostandardlib"
    },
    "NoStdLib": {
      "description": "Causes the build targets not to add an explicit reference to the `mscorlib` standard library",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#nostandardlib"
    },
    "ErrorEndLocation": {
      "description": "Causes the compiler to report the line and column of the end location of each error",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#errorendlocation"
    },
    "PreferredUILang": {
      "description": "Specifies the language to be used for compiler output such as error messages and warnings",
      "type": "culture",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#preferreduilang"
    },
    "GenerateFullPaths": {
      "description": "Cause the compiler to use full paths for filenames in output such as error messages",
      "type": "bool",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#generatefullpaths"
    },
    "AdditionalLibPaths": {
      "description": "Specifies additional directories for the compiler to search to find assemblies. This should not normally be used, as MSBuild resolves assemblies before passing them to the compiler.",
      "type": "folder",
      "isList": true,
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#additionallibpaths"
    },
    "AppConfigForCompiler": {
      "description": "Specifies the path to an `app.config` application configuration file to pass to the compiler",
      "type": "file",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#applicationconfiguration"
    },
    "PathMap": {
      "description": "Specifies how to remap physical source paths when embedding source paths in compiler output such as debug symbols. Each item in the list is of the form `mappedPath=sourcePath`.",
      "isList": true,
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced#pathmap"
    }
  },
  "items": {
    "AddModule": {
      "description": "Adds a module created with the `module` `OutputType` to the compilation.",
      "type": "file",
      "helpUrl": "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#addmodule"
    }
  },
  "types": {
  }
}

=== KirillOsenkov/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuild/Schemas/WindowsDesktop.buildschema.json
{
  "license": "Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for full license information.",
  "properties": {
    "ApplicationDefaultFont": "Customizes the application default font. The format equivalent to the output of FontConverter.ConvertToInvariantString(). Applies only to Windows Forms projects.",
    "ApplicationHighDpiMode": {
      "description": "Customizes the application DPI awareness mode. Applies only to Windows Forms projects.",
      "type": [
        "SystemAware",
        "PerMonitorV2",
        "PerMonitor",
        "DpiUnaware",
        "DpiUnawareGdiScaled"
      ]
    },
    "ApplicationUseCompatibleTextRendering": {
      "description": "Indicates whether to set UseCompatibleTextRendering property defined on certain controls (boolean). Applies only to Windows Forms projects.",
      "type": "bool"
    },
    "ApplicationVisualStyles": {
      "description": "Indicates whether to enable or disable visual styles (boolean). Applies only to Windows Forms projects.",
      "type": "bool"
    },
    "EnableDefaultPageItems": {
      "description": "Whether to include XAML page files in the project directory by wildcard",
      "type": "bool",
      "defaultValue": "true"
    },
    "EnableDefaultApplicationDefinition": {
      "description": "Whether to include XAML application files in the project directory by wildcard",
      "type": "bool",
      "defaultValue": "true"
    }
  },
  "items": {
  },
  "types": {
  }
}

=== KirillOsenkov/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuild/Schemas/RazorSdk.buildschema.json
{
  "license": "Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license. See LICENSE file in the project root for full license information.",
  "properties": {
    "EnableDefaultRazorComponentItems": {
      "description": "Set to true to automatically include Razor (.razor) files in @(RazorComponent) from @(Content).",
      "type": "bool"
    },
    "EnableDefaultRazorGenerateItems": {
      "description": "Set to true to automatically include Razor (.cshtml) files in @(RazorGenerate) from @(Content).",
      "type": "bool"
    },
    "EmbedRazorGenerateSources": {
      "description": "Configures whether all of the @(RazorGenerate) items will be added as embedded files to the produced assembly. When true, everything in @(RazorGenerate) will be added to @(RazorEmbeddedFiles) and passed to CSC.",
      "type": "bool"
    },
    "RazorCompileOnBuild": {
      "description": "Indicates whether Razor files should be compiled at build time.",
      "type": "bool"
    },
    "RazorCompileOnPublish": {
      "description": "Indicates whether Razor files should be compiled at publish time.",
      "type": "bool"
    },
    "RazorOutputPath": "Directory for Razor output.",
    "RazorTargetName": "File name (without extension) of the assembly produced by Razor.",
    "IncludeRazorContentInPack": {
      "description": "Configures whether all Razor content items (.cshtml files) will be marked to be included in the produced NuGet package as content. All Content items are included in a NuGet package as content files. This setting can be used to control this behavior for Razor content items.",
      "type": "bool"
    },
    "UseRazorBuildServer": {
      "description": "Indicates whether Razor code generation should use a persistent build server process.",
      "type": "bool"
    },
    "CopyRazorGenerateFilesToPublishDirectory": {
      "description": "Set to true to copy RazorGenerate items (.cshtml) to the publish directory. Typically Razor files are not needed for a published application if they participate in compilation at build-time or publish-time. By default, the Razor SDK will suppress the copying of RazorGenerate items to the publish directory.",
      "type": "bool"
    },
    "CopyRefAssembliesToPublishDirectory": {
      "description": "Set to true to copy reference assembly items to the publish directory. Typically reference assemblies are not needed for a published application if Razor compilation occurs at build-time or publish-time. By default, the Razor SDK will suppress the copying of reference assemblies to the publish directory.",
      "type": "bool"
    }
  },
  "items": {
  },
  "types": {
  }
}
